modLoader="javafml"
loaderVersion="[32,)"
license="GNU General Public License 3.0"
issueTrackerURL="https://github.com/MrCrayfish/Obfuscate/issues"

[[mods]]
modId="obfuscate"
version="0.6.1"
displayName="Obfuscate"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=obfuscate"
displayURL="https://mrcrayfish.com/mods?id=obfuscate"
logoFile="obfuscate_logo.png"
credits="Cheers to these people for donating during the development: Fabbe50, Infinite Worlds, ALBERT, Mastef Chief, OstenTV, Robert Finley, PlayDashGaming, Shadow Bill-cat"
authors="MrCrayfish"
description="A simple library that adds in useful events"

[[dependencies.obfuscate]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.obfuscate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"

[modproperties.obfuscate]
    catalogueImageIcon="obfuscate_icon.png"
    configuredBackground="minecraft:textures/block/yellow_concrete.png"